sudo: required
dist: trusty # Qt5, from https://gist.github.com/jreese/6207161#gistcomment-1462109

install:
  # LDTP
  - sudo apt-get install python-twisted-web
  - sudo apt-get install python-wnck
  #- sudo apt-get install python-gnome
  # Documentation
  #- sudo apt-get install rst2pdf
  # gnome-calculator, for examples/gcalctool.py
  - sudo apt-get install gnome-calculator

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  # Check python
  - which python
  - python -V
  # Build LDTP
  - python setup.py build
  - sudo python setup.py install
  # Build documentation
  # Build and run examples
  - cd examples
  - python minimal.py
  #- python gcalctool.py
  #- python gedit.py
  #- ruby test.rb
